//! Lodestone (interface 1092 on the 910 numbering) port driver (plan §9 step 4):
//! retire `build-lodestone-scripts.py`, gated on byte-exact reproduction of the
//! committed `server/cache-patches/lodestone-948/scripts/*.asm.ts`.
//!
//! Like material-storage's 9239, all three lodestone patches are **base
//! augmentation** (910→910): the base scripts 6002/6003/11674 gain switch cases +
//! appended tail blocks for the three new lodestone destinations (Fort Forinthry /
//! City of Um / Wendlewick). The base script is decoded to IR, AUTHORED IR is
//! appended (and for 11674 the final `return` is redirected to the tail), and the
//! whole is re-encoded with the validating back-end. All zero-shift on the base
//! instructions (only switch cases + appended blocks are added), so base branch
//! targets are byte-identical.

use crate::cache_bail as bail;
use crate::error::Result;
use crate::port::book::BuildDescriptor;
use crate::port::encode::ProcAllocator;
use crate::port::ir::cs2::{Cs2Ir, DbField, Insn, Operand};
use crate::port::ritual::{PortedScript, ScriptSource};
use crate::script::{SwitchCase, script_to_asm};

/// The three new lodestone components (packed uid, tooltip label). Mirrors
/// `NEW_COMS`.
const NEW_COMS: &[(i32, &str)] = &[
    (71_565_373, "Fort Forinthry"),
    (71_565_374, "City of Um"),
    (71_565_375, "Wendlewick"),
];

/// The new lodestone icon → hover-ring sprite map. Mirrors `HOVER_MAP`.
const HOVER_MAP: &[(i32, i32)] = &[(27_103, 27_050), (31_776, 31_775), (35_676, 35_675)];

/// Re-port the three lodestone base-script patches. `base_source` decodes the
/// 910-base scripts (6002/6003/11674).
pub fn port_lodestone_scripts(
    base_source: &ScriptSource<'_>,
    descriptor_910: &BuildDescriptor,
) -> Result<Vec<PortedScript>> {
    let alloc = ProcAllocator::identity();
    Ok(vec![
        patch_6002(base_source, descriptor_910, &alloc)?,
        patch_6003(base_source, descriptor_910, &alloc)?,
        patch_11674(base_source, descriptor_910, &alloc)?,
    ])
}

/// Decode a 910-base script to IR (no db-field recognition).
fn base_ir(base_source: &ScriptSource<'_>, id: i32) -> Result<Cs2Ir> {
    let no_db = |_v: i32| -> Option<DbField> { None };
    Ok(Cs2Ir::from_compiled(&base_source(id)?, &no_db))
}

/// 6002 (lodestone hover tooltip): the component switch gains cases for com61/62/63
/// → appended blocks that set the tooltip name, flag the lodestone unlocked, and
/// branch back to the common tail at 502. Mirrors `patch_6002`.
fn patch_6002(
    base_source: &ScriptSource<'_>,
    target: &BuildDescriptor,
    alloc: &ProcAllocator,
) -> Result<PortedScript> {
    let mut ir = base_ir(base_source, 6002)?;
    let base = ir.code.len() as i32;
    // Find the switch carrying `case 71565321`.
    let switch_idx = find_switch_with_case(&ir, 71_565_321)?;
    let mut at = base;
    let mut blocks: Vec<Insn> = Vec::new();
    let mut new_cases: Vec<SwitchCase> = Vec::new();
    for &(packed, label) in NEW_COMS {
        new_cases.push(SwitchCase {
            value: packed,
            target: at,
        });
        blocks.extend([
            str_const(label),
            pop_string_local(0),
            str_const(""),
            pop_string_local(1),
            int_const(1),
            pop_int_local(4),
            int_const(0),
            pop_int_local(5),
            branch(502),
        ]);
        at += 9;
    }
    if let Operand::Switch(cases) = &mut ir.code[switch_idx].operand {
        cases.extend(new_cases);
    }
    ir.code.extend(blocks);
    let body = render_asm(&ir, target, alloc)?;
    Ok(PortedScript {
        out_id: 6002,
        text: format!(
            "// lodestone-948: tooltip cases for com61 Fort Forinthry / com62 City of Um / com63 \
             Wendlewick (appended at instr {base}; zero-shift). Generated by \
             build-lodestone-scripts.py.\n{body}"
        ),
    })
}

/// 6003 (icon → hover-ring graphic): gains cases mapping the new icons to their
/// 948 hover sprites. Mirrors `patch_6003`.
fn patch_6003(
    base_source: &ScriptSource<'_>,
    target: &BuildDescriptor,
    alloc: &ProcAllocator,
) -> Result<PortedScript> {
    let mut ir = base_ir(base_source, 6003)?;
    let base = ir.code.len() as i32;
    let switch_idx = find_switch_with_case(&ir, 22_279)?;
    let mut at = base;
    let mut blocks: Vec<Insn> = Vec::new();
    let mut new_cases: Vec<SwitchCase> = Vec::new();
    for &(icon, hover) in HOVER_MAP {
        new_cases.push(SwitchCase {
            value: icon,
            target: at,
        });
        blocks.extend([int_const(hover), Insn::bare("return")]);
        at += 2;
    }
    if let Operand::Switch(cases) = &mut ir.code[switch_idx].operand {
        cases.extend(new_cases);
    }
    ir.code.extend(blocks);
    let body = render_asm(&ir, target, alloc)?;
    Ok(PortedScript {
        out_id: 6003,
        text: format!(
            "// lodestone-948: hover-ring sprites for the new lodestone icons (27103->27050, \
             31776->31775, 35676->35675; appended at instr {base}; zero-shift). Generated by \
             build-lodestone-scripts.py.\n{body}"
        ),
    })
}

/// 11674 (Teleport/Quick Teleport op-order swap): the final `return 0` is
/// redirected to an appended tail that applies the if_setop pair to the three new
/// components. Mirrors `patch_11674`.
fn patch_11674(
    base_source: &ScriptSource<'_>,
    target: &BuildDescriptor,
    alloc: &ProcAllocator,
) -> Result<PortedScript> {
    let mut ir = base_ir(base_source, 11674)?;
    let base = ir.code.len() as i32;
    // The base must end with a bare `return`.
    let last = ir.code.last().ok_or_else(|| {
        crate::error::CacheError::message("script11674 is empty")
    })?;
    if last.op != "return" {
        bail!("script11674 does not end with a bare return (got `{}`)", last.op);
    }
    let last_idx = ir.code.len() - 1;
    ir.code[last_idx] = branch(base);
    let mut blocks: Vec<Insn> = Vec::new();
    for &(packed, _) in NEW_COMS {
        for (slot, local) in [(1, 0), (2, 1)] {
            blocks.extend([
                int_const(slot),
                push_string_local(local),
                int_const(packed),
                Insn::bare("if_setop"),
            ]);
        }
    }
    blocks.push(Insn::bare("return"));
    ir.code.extend(blocks);
    let body = render_asm(&ir, target, alloc)?;
    Ok(PortedScript {
        out_id: 11674,
        text: format!(
            "// lodestone-948: Teleport/Quick Teleport op-order swap for com61/62/63 (final return \
             redirected to appended tail at instr {base}; zero-shift). Generated by \
             build-lodestone-scripts.py.\n{body}"
        ),
    })
}

/// Find the switch instruction whose case set contains `value`.
fn find_switch_with_case(ir: &Cs2Ir, value: i32) -> Result<usize> {
    ir.code
        .iter()
        .position(|i| {
            i.op == "switch"
                && matches!(&i.operand, Operand::Switch(cases) if cases.iter().any(|c| c.value == value))
        })
        .ok_or_else(|| crate::error::CacheError::message(format!("no switch with case {value}")))
}

fn render_asm(ir: &Cs2Ir, target: &BuildDescriptor, alloc: &ProcAllocator) -> Result<String> {
    let compiled = ir.to_compiled(
        &|field| target.encode_db_field(field),
        &|identity| Ok(alloc.resolve(identity)),
    )?;
    Ok(script_to_asm(&compiled))
}

// ── Small IR-instruction constructors (the authored blocks) ──────────────────

fn int_const(v: i32) -> Insn {
    Insn {
        op: "push_constant_string".into(),
        operand: Operand::TypedIntConst(v),
    }
}
fn str_const(s: &str) -> Insn {
    Insn {
        op: "push_constant_string".into(),
        operand: Operand::StrConst(s.to_string()),
    }
}
fn pop_int_local(slot: i32) -> Insn {
    Insn {
        op: "pop_int_local".into(),
        operand: Operand::LocalRef(slot),
    }
}
fn pop_string_local(slot: i32) -> Insn {
    Insn {
        op: "pop_string_local".into(),
        operand: Operand::LocalRef(slot),
    }
}
fn push_string_local(slot: i32) -> Insn {
    Insn {
        op: "push_string_local".into(),
        operand: Operand::LocalRef(slot),
    }
}
fn branch(target: i32) -> Insn {
    Insn {
        op: "branch".into(),
        operand: Operand::Jump(target),
    }
}
