//! `generate-protocol`: render the server `protocol910.ts` tables, the client
//! `protocol-910.tsv` resource, and (when `payloads.json` is present) the typed
//! `encoders910.ts` payload encoders from the schema + divergence baseline.

use super::expr::{emit_expr, parse_expr, validate_expr};
use super::types::{DivergenceBaseline, Prot, Schema, SchemaPacket};
use crate::error::{Context, Result};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// generate-protocol entry point
// ---------------------------------------------------------------------------

const GENERATED_TS_HEADER: &str = "// GENERATED by rs3-cache-rs `generate-protocol` from data/protocol/910 — do not edit.\n// Regenerate: cd tools/rs3-cache-rs && cargo run --release -- generate-protocol\n";

/// Resolved options for the `generate-protocol` subcommand.
#[derive(Debug)]
pub struct GenerateProtocolOpts<'a> {
    /// Schema directory (default `<data-dir>/protocol/910`).
    pub schema_dir: &'a Path,
    /// Root of the server checkout.
    pub server_root: &'a Path,
    /// Root of the client checkout.
    pub client_root: &'a Path,
    /// Compare-only mode: write nothing, return drift list (CLI maps to exit 3).
    pub check: bool,
}

/// The generated artifacts, in memory. The payload encoders artifact is
/// optional — only emitted when a `payloads.json` schema is present.
pub struct GenerateOutput {
    /// `(absolute path, body)` for the server `protocol910.ts`.
    pub server_ts: (PathBuf, String),
    /// `(absolute path, body)` for the client `protocol-910.tsv`.
    pub client_tsv: (PathBuf, String),
    /// `(absolute path, body)` for the server `encoders910.ts`, when
    /// `payloads.json` exists in the schema dir.
    pub encoders_ts: Option<(PathBuf, String)>,
}

// ---------------------------------------------------------------------------
// Payload schema (DSL v1) — `payloads.json`
// ---------------------------------------------------------------------------

/// One typed parameter of a packet encoder.
#[derive(Debug, Clone, serde::Deserialize, PartialEq, Eq)]
pub struct PayloadParam {
    /// Parameter name (verbatim from the encode signature).
    pub name: String,
    /// DSL type: `int` / `string` / `bigint` / `boolean`.
    #[serde(rename = "type")]
    pub ty: String,
    /// Verbatim default-value expression, when the original signature had one
    /// (preserved so the generated encoder is a drop-in for callers that omit
    /// trailing arguments). Absent for required params.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

/// One ordered codec field of a packet payload.
#[derive(Debug, Clone, serde::Deserialize, PartialEq, Eq)]
pub struct PayloadField {
    /// Write codec name (e.g. `p2_alt2`, `pjstr`).
    pub codec: String,
    /// Argument: a param name or an integer literal.
    pub arg: String,
}

/// One packet's payload schema.
#[derive(Debug, Clone, serde::Deserialize, PartialEq, Eq)]
pub struct PayloadPacket {
    /// Ordered parameters.
    pub params: Vec<PayloadParam>,
    /// Ordered codec fields (the write sequence).
    pub fields: Vec<PayloadField>,
    /// Client decode read sequence (evidence; mirror-validated).
    pub client_reads: Vec<String>,
    /// Computed (loop-free) allocation-size expression for variable-size v2
    /// packets, in the §2.2 integer grammar. Absent for fixed-size packets
    /// (their size is the schema `size`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alloc: Option<String>,
}

/// The `payloads.json` document.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct Payloads {
    /// Schema version tag (`protocol-payloads/v1` or `protocol-payloads/v2`).
    pub schema: String,
    /// Packets keyed by name.
    pub packets: BTreeMap<String, PayloadPacket>,
}

/// Count the elements of a verbatim array default like `[0, 0, 0, 0]`.
/// Returns the element count, or an error if the default isn't a bracketed list.
pub fn array_default_len(default: &str) -> Result<usize> {
    let t = default.trim();
    let inner = t
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .ok_or_else(|| {
            crate::error::CacheError::message(format!(
                "array default `{default}` is not a `[...]` literal"
            ))
        })?;
    if inner.trim().is_empty() {
        return Ok(0);
    }
    Ok(inner.split(',').filter(|s| !s.trim().is_empty()).count())
}

/// Build the scalar-param set and array-param length map for one packet.
/// Hard-errors when an `int[]` param has no default.
pub fn param_models<'a>(
    name: &str,
    params: &'a [PayloadParam],
) -> Result<(std::collections::HashSet<&'a str>, BTreeMap<&'a str, usize>)> {
    let mut scalars: std::collections::HashSet<&str> = std::collections::HashSet::new();
    let mut arrays: BTreeMap<&str, usize> = BTreeMap::new();
    for p in params {
        if p.ty == "int[]" {
            let default = p.default.as_deref().ok_or_else(|| {
                crate::error::CacheError::message(format!(
                    "payload `{name}` array param `{}` has no default",
                    p.name
                ))
            })?;
            arrays.insert(p.name.as_str(), array_default_len(default)?);
        } else {
            scalars.insert(p.name.as_str());
        }
    }
    Ok((scalars, arrays))
}

/// DSL-v1 fixed-width write codec → byte width. `None` means variable width.
pub fn codec_fixed_width(codec: &str) -> Option<u32> {
    match codec {
        "p1" | "p1_alt1" | "p1_alt2" | "p1_alt3" | "pbool" => Some(1),
        "p2" | "p2_alt1" | "p2_alt2" | "p2_alt3" => Some(2),
        "p3" => Some(3),
        "p4" | "p4_alt1" | "p4_alt2" | "p4_alt3" => Some(4),
        "p5" => Some(5),
        "p6" => Some(6),
        "p8" => Some(8),
        _ => None,
    }
}

/// Is this a DSL-v1 codec the generator understands at all (fixed or variable)?
pub fn is_v1_codec(codec: &str) -> bool {
    codec_fixed_width(codec).is_some() || codec == "pjstr" || codec == "pSmart1or2"
}

/// Mirror table (spec §1.4): the set of client read methods a write codec may
/// pair with. Width + alt variant must match; signed/byte read variants are
/// accepted (read-side signedness/charset choice).
pub fn mirror_reads(codec: &str) -> &'static [&'static str] {
    match codec {
        "p1" | "pbool" => &["g1", "g1b"],
        "p1_alt1" => &["g1_alt1", "g1b_alt1"],
        "p1_alt2" => &["g1_alt2", "g1b_alt2"],
        "p1_alt3" => &["g1_alt3", "g1b_alt3"],
        "p2" => &["g2", "g2s"],
        "p2_alt1" => &["g2_alt1", "g2s_alt1"],
        "p2_alt2" => &["g2_alt2", "g2s_alt2"],
        "p2_alt3" => &["g2_alt3"],
        "p3" => &["g3", "g3s"],
        "p4" => &["g4s", "g4"],
        "p4_alt1" => &["g4_alt1"],
        "p4_alt2" => &["g4_alt2"],
        "p4_alt3" => &["g4_alt3", "g3_alt3"],
        "p5" => &["g5"],
        "p6" => &["g6"],
        "p8" => &["g8"],
        "pjstr" => &["gjstr", "gjstr2"],
        "pSmart1or2" => &["gSmart1or2", "gSmart1or2s"],
        _ => &[],
    }
}

/// Map a DSL param type to its TS type for the generated function signature.
fn ts_param_type(ty: &str) -> &'static str {
    match ty {
        "string" => "string",
        "bigint" => "bigint",
        "boolean" => "boolean",
        "int[]" => "number[]",
        _ => "number",
    }
}

/// Convert a `SCREAMING_SNAKE` packet name to an `encodeCamelCase` function name.
pub fn encoder_fn_name(name: &str) -> String {
    let mut out = String::from("encode");
    for part in name.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            for c in chars {
                out.push(c.to_ascii_lowercase());
            }
        }
    }
    out
}

/// Load the schema for one prot from the schema directory.
fn load_schema(schema_dir: &Path, prot: Prot) -> Result<Schema> {
    let path = schema_dir.join(format!("{}_prot.json", prot.tag()));
    let text =
        fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?;
    serde_json::from_str(&text).with_context(|| format!("failed to parse {}", path.display()))
}

/// Load the divergence baseline from the schema directory.
fn load_baseline(schema_dir: &Path) -> Result<DivergenceBaseline> {
    let path = schema_dir.join("known-divergences.json");
    let text =
        fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?;
    serde_json::from_str(&text).with_context(|| format!("failed to parse {}", path.display()))
}

/// Build both generated artifacts in memory from the schema + baseline.
pub fn generate(opts: &GenerateProtocolOpts<'_>) -> Result<GenerateOutput> {
    let server = load_schema(opts.schema_dir, Prot::Server)?;
    let client = load_schema(opts.schema_dir, Prot::Client)?;
    let login = load_schema(opts.schema_dir, Prot::Login)?;
    let baseline = load_baseline(opts.schema_dir)?;

    let server_ts_body = render_server_ts(&server, &client, &login, &baseline);
    let client_tsv_body = render_client_tsv(&server, &client, &login, &baseline);

    let server_ts_path = opts
        .server_root
        .join("src/generated/protocol/protocol910.ts");
    let client_tsv_path = opts
        .client_root
        .join("client/src/test/resources/protocol-910.tsv");

    // Payload encoders: only when a `payloads.json` schema is present.
    let encoders_ts = match load_payloads(opts.schema_dir)? {
        Some(payloads) => {
            let body = render_encoders_ts(&payloads, &server)?;
            let path = opts
                .server_root
                .join("src/generated/protocol/encoders910.ts");
            Some((path, body))
        }
        None => None,
    };

    Ok(GenerateOutput {
        server_ts: (server_ts_path, server_ts_body),
        client_tsv: (client_tsv_path, client_tsv_body),
        encoders_ts,
    })
}

/// Render the server `protocol910.ts` module.
pub fn render_server_ts(
    server: &Schema,
    client: &Schema,
    login: &Schema,
    baseline: &DivergenceBaseline,
) -> String {
    let mut out = String::from(GENERATED_TS_HEADER);
    out.push('\n');
    render_ts_table(&mut out, "SERVER_PROT_910", &server.packets);
    out.push('\n');
    render_ts_table(&mut out, "CLIENT_PROT_910", &client.packets);
    out.push('\n');
    render_ts_table(&mut out, "LOGIN_PROT_910", &login.packets);
    out.push('\n');
    out.push_str("export const PROTOCOL_KNOWN_DIVERGENCES = [\n");
    for d in &baseline.divergences {
        let _ = writeln!(
            out,
            "    {{ prot: '{}', opcode: {}, check: '{}' }},",
            d.prot, d.opcode, d.check
        );
    }
    out.push_str("] as const;\n");
    out
}

/// Render one `as const` table.
fn render_ts_table(out: &mut String, export_name: &str, packets: &[SchemaPacket]) {
    let _ = writeln!(out, "export const {export_name} = [");
    for p in packets {
        let _ = writeln!(
            out,
            "    {{ name: '{}', opcode: {}, size: {} }},",
            p.name, p.opcode, p.size
        );
    }
    out.push_str("] as const;\n");
}

/// Render the client `protocol-910.tsv` resource (sorted by kind, opcode).
pub fn render_client_tsv(
    server: &Schema,
    client: &Schema,
    login: &Schema,
    baseline: &DivergenceBaseline,
) -> String {
    // Build all lines as (kind, opcode, text) so we can sort deterministically.
    let mut rows: Vec<(String, i32, String)> = Vec::new();
    for (prot, schema) in [
        (Prot::Server, server),
        (Prot::Client, client),
        (Prot::Login, login),
    ] {
        for p in &schema.packets {
            rows.push((
                prot.tag().to_owned(),
                p.opcode,
                format!("{}\t{}\t{}\t{}", prot.tag(), p.name, p.opcode, p.size),
            ));
        }
    }
    for d in &baseline.divergences {
        rows.push((
            "divergence".to_owned(),
            d.opcode,
            format!("divergence\t{}\t{}\t{}", d.prot, d.opcode, d.check),
        ));
    }
    rows.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)).then(a.2.cmp(&b.2)));

    let mut out = String::new();
    for (_, _, text) in rows {
        out.push_str(&text);
        out.push('\n');
    }
    out
}

// ---------------------------------------------------------------------------
// Payload encoder generation (`encoders910.ts`)
// ---------------------------------------------------------------------------

const GENERATED_ENCODERS_HEADER: &str = "// GENERATED by rs3-cache-rs `generate-protocol` from data/protocol/910/payloads.json — do not edit.\n// Regenerate: cd tools/rs3-cache-rs && cargo run --release -- generate-protocol\n";

/// Validate one payload packet against the schema-declared `size`, the mirror
/// table, and (Stage 8) the v2 expression grammar (field args + computed alloc).
/// Returns the variable-size flag (`true` when the schema size is `-1`/`-2`).
pub fn validate_payload(name: &str, packet: &PayloadPacket, size: i32) -> Result<bool> {
    // Mirror-symmetry: same length, each field's codec mirrors its read.
    if packet.fields.len() != packet.client_reads.len() {
        return Err(crate::error::CacheError::message(format!(
            "payload `{name}`: {} write field(s) but {} client read(s) — write/read length mismatch",
            packet.fields.len(),
            packet.client_reads.len()
        )));
    }
    for (idx, (field, read)) in packet.fields.iter().zip(&packet.client_reads).enumerate() {
        if !is_v1_codec(&field.codec) {
            return Err(crate::error::CacheError::message(format!(
                "payload `{name}` field {idx}: `{}` is not a DSL-v1 codec",
                field.codec
            )));
        }
        let allowed = mirror_reads(&field.codec);
        if !allowed.contains(&read.as_str()) {
            return Err(crate::error::CacheError::message(format!(
                "payload `{name}` field {idx}: write `{}` does not mirror client read `{}` (allowed: {})",
                field.codec,
                read,
                allowed.join(", ")
            )));
        }
    }

    // Expression args (v2): every field arg must parse in-grammar with all
    // identifiers declared and all array accesses in-bounds. v1 plain
    // param/literal args are the degenerate single-term case and pass too.
    let (scalars, arrays) = param_models(name, &packet.params)?;
    for (idx, field) in packet.fields.iter().enumerate() {
        let expr = parse_expr(&field.arg).map_err(|e| {
            crate::error::CacheError::message(format!(
                "payload `{name}` field {idx} arg `{}`: {e}",
                field.arg
            ))
        })?;
        validate_expr(
            &expr,
            &scalars,
            &arrays,
            &format!("payload `{name}` field {idx} arg"),
        )?;
    }

    // Size: fixed packets must have sum-of-fixed-widths == schema size; variable
    // packets (-1/-2) must contain at least one variable codec OR carry a
    // computed `alloc` expression (Stage 8). Expression args do not change codec
    // widths, so the fixed-size sum check is unchanged.
    let variable = size < 0;
    let mut fixed_sum: u32 = 0;
    let mut has_variable = false;
    for field in &packet.fields {
        match codec_fixed_width(&field.codec) {
            Some(w) => fixed_sum += w,
            None => has_variable = true,
        }
    }

    // A computed `alloc` is validated against the same grammar/param model.
    if let Some(alloc) = &packet.alloc {
        let expr = parse_expr(alloc).map_err(|e| {
            crate::error::CacheError::message(format!("payload `{name}` alloc `{alloc}`: {e}"))
        })?;
        validate_expr(&expr, &scalars, &arrays, &format!("payload `{name}` alloc"))?;
    }

    if variable {
        if !has_variable && packet.alloc.is_none() {
            return Err(crate::error::CacheError::message(format!(
                "payload `{name}`: schema size {size} is variable but neither a variable-width codec nor a computed `alloc` is present"
            )));
        }
    } else {
        if has_variable {
            return Err(crate::error::CacheError::message(format!(
                "payload `{name}`: schema size {size} is fixed but a variable-width codec is present"
            )));
        }
        if packet.alloc.is_some() {
            return Err(crate::error::CacheError::message(format!(
                "payload `{name}`: schema size {size} is fixed but a computed `alloc` is present"
            )));
        }
        let declared = u32::try_from(size).unwrap_or(0);
        if fixed_sum != declared {
            return Err(crate::error::CacheError::message(format!(
                "payload `{name}`: fixed-size sum {fixed_sum} != schema size {declared}"
            )));
        }
    }
    Ok(variable)
}

/// Render the size expression for a packet's `new Packet(new Uint8Array(<expr>))`.
///
/// A v2 computed `alloc` (emitted canonically) wins when present. Otherwise:
/// fixed packets emit the literal byte count; variable packets emit a sum of
/// fixed-width terms plus `x.length + 1` for `pjstr` and `(v < 128 ? 1 : 2)`
/// for `pSmart1or2`.
pub fn render_size_expr(packet: &PayloadPacket) -> Result<String> {
    if let Some(alloc) = &packet.alloc {
        // Re-emit the alloc expression canonically (already validated).
        return Ok(emit_expr(&parse_expr(alloc)?));
    }
    let mut terms: Vec<String> = Vec::new();
    let mut fixed: u32 = 0;
    for field in &packet.fields {
        match codec_fixed_width(&field.codec) {
            Some(w) => fixed += w,
            None => match field.codec.as_str() {
                "pjstr" => terms.push(format!("{}.length + 1", field.arg)),
                "pSmart1or2" => terms.push(format!("({} < 128 ? 1 : 2)", field.arg)),
                _ => {}
            },
        }
    }
    if terms.is_empty() {
        return Ok(fixed.to_string());
    }
    // Leading fixed total first (when non-zero), then variable terms in order.
    let mut all: Vec<String> = Vec::new();
    if fixed > 0 {
        all.push(fixed.to_string());
    }
    all.extend(terms);
    Ok(all.join(" + "))
}

/// Render one exported typed encoder function. Field args are re-emitted from
/// their parsed AST so array accesses gain a strict-tsc `!` and the canonical
/// parenthesization is reproduced verbatim.
fn render_encoder_fn(out: &mut String, name: &str, packet: &PayloadPacket) -> Result<()> {
    let fn_name = encoder_fn_name(name);
    let sig_params: Vec<String> = packet
        .params
        .iter()
        .map(|p| match &p.default {
            Some(d) => format!("{}: {} = {}", p.name, ts_param_type(&p.ty), d),
            None => format!("{}: {}", p.name, ts_param_type(&p.ty)),
        })
        .collect();
    let _ = writeln!(
        out,
        "export function {fn_name}({}): Packet {{",
        sig_params.join(", ")
    );
    let _ = writeln!(
        out,
        "    const buf: Packet = new Packet(new Uint8Array({}));",
        render_size_expr(packet)?
    );
    for field in &packet.fields {
        let arg = emit_expr(&parse_expr(&field.arg)?);
        let _ = writeln!(out, "    buf.{}({});", field.codec, arg);
    }
    out.push_str("    return buf;\n}\n");
    Ok(())
}

/// Render the full `encoders910.ts` module from the payload schema (validated
/// against the server schema sizes). Returns an error on the first validation
/// failure (size sum or mirror symmetry).
pub fn render_encoders_ts(payloads: &Payloads, server: &Schema) -> Result<String> {
    if payloads.schema != "protocol-payloads/v1" && payloads.schema != "protocol-payloads/v2" {
        return Err(crate::error::CacheError::message(format!(
            "unexpected payloads schema `{}` (want protocol-payloads/v1 or /v2)",
            payloads.schema
        )));
    }
    let size_by_name: BTreeMap<&str, i32> = server
        .packets
        .iter()
        .map(|p| (p.name.as_str(), p.size))
        .collect();

    // Validate every packet before emitting anything.
    for (name, packet) in &payloads.packets {
        let size = size_by_name.get(name.as_str()).copied().ok_or_else(|| {
            crate::error::CacheError::message(format!(
                "payload `{name}` has no entry in server_prot.json schema"
            ))
        })?;
        validate_payload(name, packet, size)?;
    }

    let mut out = String::from(GENERATED_ENCODERS_HEADER);
    out.push('\n');
    out.push_str("import Packet from '#jagex/bytepacking/Packet.js';\n\n");
    let mut first = true;
    for (name, packet) in &payloads.packets {
        if !first {
            out.push('\n');
        }
        first = false;
        render_encoder_fn(&mut out, name, packet)?;
    }
    Ok(out)
}

/// Load `payloads.json` from the schema dir, if present.
fn load_payloads(schema_dir: &Path) -> Result<Option<Payloads>> {
    let path = schema_dir.join("payloads.json");
    if !path.is_file() {
        return Ok(None);
    }
    let text =
        fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?;
    let payloads: Payloads = serde_json::from_str(&text)
        .with_context(|| format!("failed to parse {}", path.display()))?;
    Ok(Some(payloads))
}

/// Run the `generate-protocol` subcommand. Returns `true` when `--check` found
/// drift (the CLI maps that to exit code 3).
pub fn run_generate(opts: &GenerateProtocolOpts<'_>) -> Result<bool> {
    let output = generate(opts)?;
    let mut artifacts: Vec<&(PathBuf, String)> = vec![&output.server_ts, &output.client_tsv];
    if let Some(enc) = &output.encoders_ts {
        artifacts.push(enc);
    }

    if opts.check {
        let mut drift: Vec<&Path> = Vec::new();
        for (path, body) in &artifacts {
            let on_disk = fs::read_to_string(path).unwrap_or_default();
            if on_disk != *body {
                drift.push(path);
            }
        }
        if drift.is_empty() {
            println!(
                "generate-protocol --check: all {} artifact(s) up to date",
                artifacts.len()
            );
            return Ok(false);
        }
        println!(
            "generate-protocol --check: {} artifact(s) differ:",
            drift.len()
        );
        for path in &drift {
            println!("  - {}", path.display());
        }
        return Ok(true);
    }

    for (path, body) in &artifacts {
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir)
                .with_context(|| format!("failed to create {}", dir.display()))?;
        }
        fs::write(path, body).with_context(|| format!("failed to write {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(false)
}
