#!/usr/bin/env python3
"""Extract CS2 opcode stack effects from the client's ScriptRunner.

Each opcode handler in ScriptRunner is a static method whose body manipulates
three operand stacks via the state's `isp` (int), `osp` (object/string) and
`lsp` (long) pointers:

    pop  : `--arg0.isp`, `arg0.isp--`, `arg0.isp -= N`
    push : `++arg0.isp`, `arg0.isp++`, `arg0.isp += N`

The net change per stack is the opcode's stack effect. We key the table by the
handler's method name, which matches the opcode command names in
`data/opcodes-*.txt`, and emit `data/stack-effects.txt`:

    <command> <pops> <pushes> <type>

where `type` is the pushed value's stack (int/obj/long), `none` for a void
opcode, or `multi` when more than one stack is pushed.

Only handlers with at least one *direct* stack op and no loop are emitted, so
the table never overrides the conservative categorisation default with a guess
for a delegating or variable-effect handler. Stack effects are build
independent (an opcode does the same thing on 910 and 947), so one table serves
all builds. The recompile-fidelity gate is the backstop for any residual
mis-extraction: a wrong effect simply leaves its scripts blocked, never
corrupts.

Usage:
    extract-stack-effects.py [SCRIPTRUNNER.java] [OPCODES.txt ...] > data/stack-effects.txt
"""

import re
import sys

DEFAULT_RUNNER = (
    "/Users/robert/projects/alerion/client/client/src/main/java/"
    "rs2/client/clientscript/ScriptRunner.java"
)
DEFAULT_OPCODES = [
    "data/opcodes-947.txt",
    "data/opcodes-910.txt",
]

# Handlers with a trailing compile-time variant flag (`..., boolean arg1`) are
# deliberately excluded: their push is often conditional on the flag, so a
# static count mis-models them (e.g. db_find). Single-state-arg handlers only.
HANDLER_RE = re.compile(
    r"public static final void (\w+)\(ClientScriptState arg0\)\s*\{"
)


def handler_body(text, open_brace):
    """Return the body of a method whose `{` is at index `open_brace`."""
    depth = 0
    for i in range(open_brace, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1 : i]
    return text[open_brace + 1 :]


def stack_delta(body, ptr):
    """(pops, pushes) for one stack pointer (`isp`/`osp`/`lsp`)."""
    pops = len(re.findall(rf"--arg0\.{ptr}\b", body))
    pops += len(re.findall(rf"arg0\.{ptr}--", body))
    pops += sum(int(n) for n in re.findall(rf"arg0\.{ptr} -= (\d+)", body))
    pushes = len(re.findall(rf"\+\+arg0\.{ptr}\b", body))
    pushes += len(re.findall(rf"arg0\.{ptr}\+\+", body))
    pushes += sum(int(n) for n in re.findall(rf"arg0\.{ptr} \+= (\d+)", body))
    return pops, pushes


def main():
    args = sys.argv[1:]
    runner = args[0] if args else DEFAULT_RUNNER
    opcode_files = args[1:] if len(args) > 1 else DEFAULT_OPCODES

    known = set()
    for path in opcode_files:
        try:
            with open(path) as fh:
                for line in fh:
                    name = line.split(",", 1)[0].strip()
                    if name:
                        known.add(name)
        except OSError:
            pass

    text = open(runner).read()
    rows = {}
    for m in HANDLER_RE.finditer(text):
        name = m.group(1)
        if known and name not in known:
            continue
        body = handler_body(text, m.end() - 1)
        # Loops give variable stack effects we cannot count statically.
        if re.search(r"\b(for|while)\s*\(", body):
            continue
        ip, iu = stack_delta(body, "isp")
        op, ou = stack_delta(body, "osp")
        lp, lu = stack_delta(body, "lsp")
        pops = ip + op + lp
        pushes = iu + ou + lu
        # Only emit when there is direct stack evidence; otherwise leave the
        # opcode to the categorisation default rather than guess.
        if pops == 0 and pushes == 0:
            continue
        pushed = [(iu, "int"), (ou, "obj"), (lu, "long")]
        nonzero = [t for n, t in pushed if n > 0]
        if not nonzero:
            kind = "none"
        elif len(nonzero) == 1:
            kind = nonzero[0]
        else:
            kind = "multi"
        rows[name] = (pops, pushes, kind)

    print("# command pops pushes type")
    print("# generated by scripts/extract-stack-effects.py from the client ScriptRunner")
    for name in sorted(rows):
        pops, pushes, kind = rows[name]
        print(f"{name} {pops} {pushes} {kind}")


if __name__ == "__main__":
    main()
