pub const BUILD: u32 = 947;
pub const SUBBUILD: u32 = 1;

pub const ARCHIVE_CONFIG: u32 = 2;
pub const ARCHIVE_INTERFACES: u32 = 3;
pub const ARCHIVE_SYNTH: u32 = 4;
pub const ARCHIVE_MAPSQUARES: u32 = 5;
pub const ARCHIVE_SONGS: u32 = 6;
pub const ARCHIVE_TEXTURES: u32 = 9;
pub const ARCHIVE_BINARY: u32 = 10;
pub const ARCHIVE_JINGLES: u32 = 11;
pub const ARCHIVE_CLIENTSCRIPTS: u32 = 12;
pub const ARCHIVE_CHUNK_INSTANCES: u32 = 0x29;
pub const ARCHIVE_LOC_CONFIG: u32 = 16;
pub const ARCHIVE_ENUM_CONFIG: u32 = 17;
pub const ARCHIVE_NPC_CONFIG: u32 = 18;
pub const ARCHIVE_OBJ_CONFIG: u32 = 19;
pub const ARCHIVE_SEQ_CONFIG: u32 = 20;
pub const ARCHIVE_SPOT_CONFIG: u32 = 21;
pub const ARCHIVE_QUICKCHAT_CONFIG: u32 = 24;
pub const ARCHIVE_MATERIALS: u32 = 26;
pub const ARCHIVE_PARTICLES: u32 = 27;
pub const ARCHIVE_DEFAULTS: u32 = 28;
pub const ARCHIVE_BILLBOARDS: u32 = 29;
pub const ARCHIVE_STRUCT_CONFIG: u32 = 22;
pub const ARCHIVE_VORBIS: u32 = 14;
pub const ARCHIVE_AUDIOSTREAMS: u32 = 40;
pub const ARCHIVE_MODELS_RT7: u32 = 47;
pub const ARCHIVE_ACHIEVEMENTS: u32 = 57;
pub const ARCHIVE_FONTMETRICS: u32 = 58;
pub const ARCHIVE_TTF: u32 = 59;
pub const ARCHIVE_STYLESHEETS: u32 = 60;
pub const ARCHIVE_VFX: u32 = 61;
pub const ARCHIVE_ANIMATOR: u32 = 62;
pub const ARCHIVE_UI_ANIM: u32 = 65;
pub const ARCHIVE_CUTSCENE2D: u32 = 66;
pub const ARCHIVE_WORLDMAP: u32 = 23;

pub const CONFIG_GROUP_UNDERLAY: u32 = 1;
pub const CONFIG_GROUP_PARTICLE_EMITTER_ARCHIVE27: u32 = 0;
pub const CONFIG_GROUP_IDK: u32 = 3;
pub const CONFIG_GROUP_INV: u32 = 5;
pub const CONFIG_GROUP_LOC_LEGACY: u32 = 6;
pub const CONFIG_GROUP_MESANIM: u32 = 7;
pub const CONFIG_GROUP_HUNT: u32 = 2;
pub const CONFIG_GROUP_OVERLAY: u32 = 4;
pub const CONFIG_GROUP_PARAM: u32 = 11;
pub const CONFIG_GROUP_OBJ_LEGACY: u32 = 10;
pub const CONFIG_GROUP_NPC_LEGACY: u32 = 9;
pub const CONFIG_GROUP_SEQ: u32 = 12;
pub const CONFIG_GROUP_SPOT: u32 = 13;
pub const CONFIG_GROUP_VAR_CLIENT_STRING: u32 = 15;
pub const CONFIG_GROUP_AREA: u32 = 18;
pub const CONFIG_GROUP_VAR_SHARED: u32 = 22;
pub const CONFIG_GROUP_VAR_SHARED_STRING: u32 = 23;
pub const CONFIG_GROUP_QUICKCHATCAT_ARCHIVE24: u32 = 0;
pub const CONFIG_GROUP_QUICKCHATPHRASE_ARCHIVE24: u32 = 1;
pub const CONFIG_GROUP_PARTICLE_EFFECTOR_ARCHIVE27: u32 = 1;
pub const CONFIG_GROUP_VAR_NPC_BIT: u32 = 25;
pub const CONFIG_GROUP_SKYBOX: u32 = 29;
pub const CONFIG_GROUP_LIGHT: u32 = 31;
pub const CONFIG_GROUP_BAS: u32 = 32;
pub const CONFIG_GROUP_BILLBOARD_ARCHIVE29: u32 = 0;
pub const CONFIG_GROUP_MSI: u32 = 34;
pub const CONFIG_GROUP_QUEST: u32 = 35;
pub const CONFIG_GROUP_MEL: u32 = 36;
pub const CONFIG_GROUP_STRUCT: u32 = 26;
pub const CONFIG_GROUP_CURSOR: u32 = 33;
pub const CONFIG_GROUP_DBTABLE: u32 = 40;
pub const CONFIG_GROUP_DBROW: u32 = 41;
pub const CONFIG_GROUP_CONTROLLER: u32 = 42;
pub const CONFIG_GROUP_HITMARK: u32 = 46;
pub const CONFIG_GROUP_ITEMCODE: u32 = 48;
pub const CONFIG_GROUP_CATEGORY: u32 = 49;
pub const CONFIG_GROUP_GAMELOGEVENT: u32 = 70;
pub const CONFIG_GROUP_HEADBAR: u32 = 72;
pub const CONFIG_GROUP_BUGTEMPLATE: u32 = 73;
pub const CONFIG_GROUP_WATER: u32 = 76;
pub const CONFIG_GROUP_SEQGROUP: u32 = 77;
pub const CONFIG_GROUP_WORLDAREA: u32 = 83;
pub const CONFIG_GROUP_ACHIEVEMENT_ARCHIVE57: u32 = 7;
pub const CONFIG_GROUP_MATERIAL_ARCHIVE26: u32 = 0;
pub const CONFIG_GROUP_VAR_PLAYER: u32 = 60;
pub const CONFIG_GROUP_VAR_NPC: u32 = 61;
pub const CONFIG_GROUP_VAR_CLIENT: u32 = 62;
pub const CONFIG_GROUP_VAR_WORLD: u32 = 63;
pub const CONFIG_GROUP_VAR_REGION: u32 = 64;
pub const CONFIG_GROUP_VAR_OBJECT: u32 = 65;
pub const CONFIG_GROUP_VAR_CLAN: u32 = 66;
pub const CONFIG_GROUP_VAR_CLAN_SETTING: u32 = 67;
pub const CONFIG_GROUP_VAR_CONTROLLER: u32 = 68;
pub const CONFIG_GROUP_VAR_BIT: u32 = 69;
pub const CONFIG_GROUP_VAR_GLOBAL: u32 = 75;
pub const CONFIG_GROUP_VAR_PLAYER_GROUP: u32 = 80;
pub const DEFAULTS_GROUP_GRAPHICS: u32 = 3;
pub const DEFAULTS_GROUP_AUDIO: u32 = 4;
pub const DEFAULTS_GROUP_WEARPOS: u32 = 6;
pub const DEFAULTS_GROUP_WORLDMAP: u32 = 10;
pub const DEFAULTS_GROUP_TITLE: u32 = 12;

pub const AUDIO_ARCHIVES: [u32; 5] = [
    ARCHIVE_SYNTH,
    ARCHIVE_SONGS,
    ARCHIVE_JINGLES,
    ARCHIVE_VORBIS,
    ARCHIVE_AUDIOSTREAMS,
];

pub const DEFAULT_CACHE_TAR: &str =
    "cache-runescape-live-en-b947.1-2026-04-20-10-45-34-openrs2#2519.tar";
