//! `generate-cs2-data` — regenerate the hand-maintained opcode txt files for
//! build 910 as deterministic *views* of the extracted CS2 registry.
//!
//! Three outputs (all sorted by id, LF line endings, trailing newline):
//! - `opcodes-910.txt`        — `name,id` for all 1,432 commands;
//! - `opcodes-large-910.txt`  — `id,flag` for all 1,432 ids;
//! - `opcode-aliases-910.txt` — `alt,canonical` sorted by alt.
//!
//! `opcodes-948.txt` is intentionally NOT regenerated: the registry is anchored
//! to the 1,432-case 910 dispatch switch and cannot represent the donor-only
//! opcodes that appear in `opcodes-948.txt` (e.g. `sub` at id 824) but have no
//! 910 command. Those are used when decoding the live 948 cache, so 948 — like
//! the legacy 947 donor — stays hand-derived. See `OpcodeBook::load` /
//! `tests/cs2_opcode_registry_equiv.rs` for the proof.
//!
//! Read-only over the registry; writes only the three 910 views (or, with
//! `--check`, writes nothing and reports drift). No timestamps; deterministic.
//!
//! Example invocation:
//!
//! ```bash
//! cd tools/rs3-cache-rs
//! cargo run --release -- generate-cs2-data --check
//! ```

use crate::error::{Context, Result};
use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};

/// Schema string the generator accepts.
const REGISTRY_SCHEMA: &str = "cs2-registry/v3";

/// Resolved options for the `generate-cs2-data` subcommand.
#[derive(Debug)]
pub struct Cs2DataGenOpts<'a> {
    /// Registry JSON path (default: `<data-dir>/cs2/registry-910.json`).
    pub registry: Option<&'a Path>,
    /// Output directory for the generated views (default: `<data-dir>`).
    pub out_dir: Option<&'a Path>,
    /// Global data directory (default registry path + default out dir).
    pub data_dir: &'a Path,
    /// Compare-only mode: write nothing; exit 3 on any difference.
    pub check: bool,
}

/// Minimal projection of the registry needed to emit the views.
#[derive(Debug, Deserialize)]
struct RegistryDoc {
    schema: String,
    commands: Vec<RegistryCommand>,
}

#[derive(Debug, Deserialize)]
struct RegistryCommand {
    name: String,
    id_910: u16,
    large_operand: bool,
    aliases: Vec<String>,
}

/// `opcodes-910.txt` header (3 generated `//` lines).
const OPCODES_910_HEADER: &str = "\
// GENERATED by `generate-cs2-data` from cs2/registry-910.json — do not hand-edit.
// Truth chain: client ScriptRunner/Cs2Dispatch → extract-cs2-registry → this view.
// name,id — canonical 910 command names.
";

/// `opcodes-large-910.txt` header (2 generated `//` lines).
const OPCODES_LARGE_910_HEADER: &str = "\
// GENERATED by `generate-cs2-data` from cs2/registry-910.json — do not hand-edit.
// id,flag — generic-operand width fallback per 910 opcode id.
";

/// `opcode-aliases-910.txt` header: the first line is the GENERATED marker, the
/// remaining lines preserve the existing explanatory comments verbatim.
const OPCODE_ALIASES_910_HEADER: &str = "\
// GENERATED by `generate-cs2-data` from cs2/registry-910.json — do not hand-edit.
// Format: <alt_name>,<canonical_910_name>
// Maps a cross-build opcode name (left, e.g. the name 947 uses) to this build's
// canonical name (right) for the SAME engine opcode. Consulted ONLY when a direct
// name->index lookup misses, so decode / name() output is unchanged.
//
// Verified same opcode, different name across builds:
//   947 `enum` (idx 1660)  ==  910 `_enum` (idx 810)   — config enum read; stack args, no inline operand.
";

/// Run the `generate-cs2-data` subcommand. Returns `true` when `--check` found
/// drift (the CLI maps that to exit code 3).
pub fn run(opts: &Cs2DataGenOpts<'_>) -> Result<bool> {
    let registry_path: PathBuf = opts.registry.map_or_else(
        || opts.data_dir.join("cs2").join("registry-910.json"),
        Path::to_path_buf,
    );
    let out_dir: PathBuf = opts
        .out_dir
        .map_or_else(|| opts.data_dir.to_path_buf(), Path::to_path_buf);

    let content = fs::read_to_string(&registry_path)
        .with_context(|| format!("failed reading registry {}", registry_path.display()))?;
    let doc: RegistryDoc = serde_json::from_str(&content)
        .with_context(|| format!("failed parsing registry {}", registry_path.display()))?;
    if doc.schema != REGISTRY_SCHEMA {
        crate::cache_bail!(
            "registry {} has schema '{}', expected '{REGISTRY_SCHEMA}'",
            registry_path.display(),
            doc.schema
        );
    }

    let views = render_views(&doc.commands);

    if opts.check {
        let mut drift: Vec<String> = Vec::new();
        for (name, body) in &views {
            let path = out_dir.join(name);
            let on_disk = fs::read_to_string(&path).unwrap_or_default();
            if on_disk != *body {
                drift.push((*name).to_owned());
            }
        }
        if drift.is_empty() {
            println!(
                "generate-cs2-data --check: all {} view(s) up to date",
                views.len()
            );
            return Ok(false);
        }
        println!("generate-cs2-data --check: {} view(s) differ:", drift.len());
        for name in &drift {
            println!("  - {name}");
        }
        return Ok(true);
    }

    for (name, body) in &views {
        let path = out_dir.join(name);
        fs::write(&path, body).with_context(|| format!("failed writing {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(false)
}

/// Render the three generated views as `(file_name, full_body)` pairs.
fn render_views(commands: &[RegistryCommand]) -> Vec<(&'static str, String)> {
    // Sort ascending by id (the registry is already id-ordered, but do not rely on it).
    let mut by_id: Vec<&RegistryCommand> = commands.iter().collect();
    by_id.sort_by_key(|c| c.id_910);

    // opcodes-910.txt
    let mut opcodes = String::from(OPCODES_910_HEADER);
    for cmd in &by_id {
        opcodes.push_str(&cmd.name);
        opcodes.push(',');
        opcodes.push_str(&cmd.id_910.to_string());
        opcodes.push('\n');
    }

    // opcodes-large-910.txt
    let mut large = String::from(OPCODES_LARGE_910_HEADER);
    for cmd in &by_id {
        large.push_str(&cmd.id_910.to_string());
        large.push(',');
        large.push(if cmd.large_operand { '1' } else { '0' });
        large.push('\n');
    }

    // opcode-aliases-910.txt — rows are `alt,canonical` sorted by alt.
    let mut alias_rows: Vec<(String, String)> = Vec::new();
    for cmd in commands {
        for alt in &cmd.aliases {
            alias_rows.push((alt.clone(), cmd.name.clone()));
        }
    }
    alias_rows.sort();
    let mut aliases = String::from(OPCODE_ALIASES_910_HEADER);
    for (alt, canonical) in &alias_rows {
        aliases.push_str(alt);
        aliases.push(',');
        aliases.push_str(canonical);
        aliases.push('\n');
    }

    vec![
        ("opcodes-910.txt", opcodes),
        ("opcodes-large-910.txt", large),
        ("opcode-aliases-910.txt", aliases),
    ]
}

#[cfg(test)]
mod tests {
    use super::{Cs2DataGenOpts, RegistryCommand, render_views, run};
    use crate::error::Result;
    use std::fs;
    use tempfile::tempdir;

    fn cmd(name: &str, id: u16, large: bool, aliases: &[&str]) -> RegistryCommand {
        RegistryCommand {
            name: name.to_owned(),
            id_910: id,
            large_operand: large,
            aliases: aliases.iter().map(|s| (*s).to_owned()).collect(),
        }
    }

    #[test]
    fn views_are_id_sorted_and_well_formed() {
        // Deliberately out of order to prove sorting.
        let commands = vec![
            cmd("_enum", 810, false, &["enum"]),
            cmd("push_constant_int", 204, true, &[]),
            cmd("add", 842, false, &[]),
        ];
        let views = render_views(&commands);
        let opcodes = &views[0].1;
        assert!(opcodes.starts_with("// GENERATED"));
        // id-sorted: 204 before 810 before 842.
        let body: Vec<&str> = opcodes.lines().filter(|l| !l.starts_with("//")).collect();
        assert_eq!(body, vec!["push_constant_int,204", "_enum,810", "add,842"]);

        let large = &views[1].1;
        let lbody: Vec<&str> = large.lines().filter(|l| !l.starts_with("//")).collect();
        assert_eq!(lbody, vec!["204,1", "810,0", "842,0"]);

        let aliases = &views[2].1;
        assert!(aliases.starts_with("// GENERATED"));
        let abody: Vec<&str> = aliases.lines().filter(|l| !l.starts_with("//")).collect();
        assert_eq!(abody, vec!["enum,_enum"]);
        // trailing newline on every view
        for (_, b) in &views {
            assert!(b.ends_with('\n'));
        }
    }

    #[test]
    fn write_then_check_is_clean_and_double_run_identical() -> Result<()> {
        let dir = tempdir()?;
        let registry = dir.path().join("cs2/registry-910.json");
        fs::create_dir_all(registry.parent().expect("registry parent dir"))?;
        fs::write(
            &registry,
            r#"{"schema":"cs2-registry/v3","commands":[
                {"name":"add","id_910":842,"large_operand":false,"aliases":[]},
                {"name":"_enum","id_910":810,"large_operand":false,"aliases":["enum"]}
            ]}"#,
        )?;

        // Write the views.
        let drift = run(&Cs2DataGenOpts {
            registry: Some(&registry),
            out_dir: Some(dir.path()),
            data_dir: dir.path(),
            check: false,
        })?;
        assert!(!drift);

        // Capture bytes, run again, assert byte-identical.
        let first: Vec<Vec<u8>> = [
            "opcodes-910.txt",
            "opcodes-large-910.txt",
            "opcode-aliases-910.txt",
        ]
        .iter()
        .map(|n| fs::read(dir.path().join(n)).expect("read generated view"))
        .collect();
        run(&Cs2DataGenOpts {
            registry: Some(&registry),
            out_dir: Some(dir.path()),
            data_dir: dir.path(),
            check: false,
        })?;
        for (i, n) in [
            "opcodes-910.txt",
            "opcodes-large-910.txt",
            "opcode-aliases-910.txt",
        ]
        .iter()
        .enumerate()
        {
            assert_eq!(
                first[i],
                fs::read(dir.path().join(n)).expect("re-read generated view"),
                "{n} not deterministic"
            );
        }

        // --check now reports no drift.
        let drift = run(&Cs2DataGenOpts {
            registry: Some(&registry),
            out_dir: Some(dir.path()),
            data_dir: dir.path(),
            check: true,
        })?;
        assert!(!drift, "check should be clean after a fresh write");

        // Mutate a file → --check reports drift.
        fs::write(dir.path().join("opcodes-910.txt"), "// tampered\n")?;
        let drift = run(&Cs2DataGenOpts {
            registry: Some(&registry),
            out_dir: Some(dir.path()),
            data_dir: dir.path(),
            check: true,
        })?;
        assert!(drift, "check should detect drift");

        Ok(())
    }
}
