#![deny(clippy::dbg_macro, clippy::todo, clippy::unimplemented)]
// `unwrap_used` is enforced in production builds only; `.unwrap()` is idiomatic in unit tests.
#![cfg_attr(not(test), deny(clippy::unwrap_used))]
// The curated policy allow-list lives in `Cargo.toml [lints.clippy]` so it applies to ALL targets
// (lib, bins, examples, tests) — a crate-level `#![allow]` here would not reach the separate
// example/test crates.

pub mod animator;
pub mod audio;
pub mod cache;
pub mod cli;
pub mod collision;
pub mod commands;
pub mod config;
pub mod config_dump;
pub mod config_refs;
pub mod config_transcode;
pub mod constants;
pub mod cs2;
pub mod cs2_coverage;
pub mod cs2_datagen;
pub mod cs2_javagen;
pub mod cs2_registry;
pub mod cutscene2d;
pub mod data_closure;
pub mod decode;
pub mod dep_tree;
pub mod discover;
pub mod dump;
pub mod error;
pub mod explain;
pub mod explain_loc;
pub mod explain_transitive;
pub mod fixture;
pub mod font;
pub mod interface;
pub mod interface_codec;
pub mod js5;
pub mod js5pack;
pub mod map;
pub mod migrate;
pub mod model;
pub mod opcode_book;
pub mod overlay_deps;
pub mod overlay_manifest;
pub mod overlay_plan;
pub mod pack_root;
pub mod packet;
pub mod parallel;
pub mod port;
pub mod protocol_registry;
pub mod script;
pub mod script_transpile;
pub mod stack_effects;
pub mod transpile;
pub mod ts_idgen;
pub mod validate;
pub mod vars;
pub mod vfx;
