//! `extract-stack-effects` — derive the CS2 opcode stack-effect table from the
//! client's clientscript handler sources (the port of the retired
//! `scripts/extract-stack-effects.py`).
//!
//! Each opcode handler is a `public static final void NAME(ClientScriptState
//! arg0) { … }` static method whose body manipulates three operand stacks via
//! the state's `isp` (int), `osp` (object/string) and `lsp` (long) pointers:
//!
//! ```text
//! pop  : `--arg0.isp`, `arg0.isp--`, `arg0.isp -= N`
//! push : `++arg0.isp`, `arg0.isp++`, `arg0.isp += N`
//! ```
//!
//! The net change per stack is the opcode's stack effect. The table is keyed by
//! the handler's method name, which matches the opcode command names in
//! `data/opcodes-*.txt`, and emits `data/stack-effects.txt`:
//!
//! ```text
//! <command> int_pops obj_pops long_pops int_pushes obj_pushes long_pushes
//! ```
//!
//! Only handlers with at least one *direct* stack op and no loop are emitted, so
//! the table never overrides the conservative categorisation default with a
//! guess for a delegating or variable-effect handler. Stack effects are build
//! independent (an opcode does the same thing on 910 and 948), so one table
//! serves all builds.
//!
//! Unlike the retired Python (which read one hardcoded `ScriptRunner.java`), this
//! globs *every* `*.java` in the clientscript package. The handlers were split
//! out of `ScriptRunner` into sibling `*Ops.java` classes (`CcOps`, `IfOps`, …),
//! so reading the whole directory is what keeps the extraction whole across
//! future class moves. `tests/stack_effects_oracle.rs` is the regression gate.

use crate::error::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Default clientscript package directory (holds `ScriptRunner.java` plus the
/// `*Ops.java` handler classes), relative to the crate dir the CLI runs from.
pub const DEFAULT_CLIENTSCRIPT_DIR: &str =
    "../../client/client/src/main/java/rs2/client/clientscript";

/// Default opcode-name sources: a command is emitted only when its handler name
/// is a known opcode in at least one of these books.
pub const DEFAULT_OPCODE_FILES: &[&str] = &["data/opcodes-947.txt", "data/opcodes-910.txt"];

/// Default output path for the generated table.
pub const DEFAULT_OUT: &str = "data/stack-effects.txt";

/// The two `#`-prefixed header lines that prefix the generated table. The first
/// names the columns; the second records provenance.
///
/// Header for `data/stack-effects.txt`: the column legend plus a provenance line
/// naming the generator — this `extract-stack-effects` subcommand, which reads the
/// whole client `clientscript` package (`ScriptRunner.java` + the `*Ops` classes).
/// `tests/stack_effects_oracle.rs` pins the regenerated bytes against the file.
const HEADER: &str = "# command int_pops obj_pops long_pops int_pushes obj_pushes long_pushes\n# generated by rs3-cache-rs `extract-stack-effects` from the client clientscript handlers\n";

/// Options for [`run`] / [`extract`].
pub struct ExtractStackEffectsOpts<'a> {
    /// Directory globbed for `*.java` handler sources.
    pub clientscript_dir: &'a Path,
    /// Opcode-name books; a handler is kept only when its name appears in one.
    pub opcode_files: &'a [PathBuf],
    /// Output path for the generated table.
    pub out: &'a Path,
}

/// One handler's net stack effect (pops/pushes per operand stack).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct StackEffect {
    int_pops: u32,
    obj_pops: u32,
    long_pops: u32,
    int_pushes: u32,
    obj_pushes: u32,
    long_pushes: u32,
}

impl StackEffect {
    /// True when the handler touched no stack pointer at all — such handlers are
    /// left to the categorisation default rather than recorded as all-zero.
    const fn is_empty(self) -> bool {
        self.int_pops
            + self.obj_pops
            + self.long_pops
            + self.int_pushes
            + self.obj_pushes
            + self.long_pushes
            == 0
    }
}

/// Run the extraction and write the table to `opts.out`. Returns the exact bytes
/// written so callers (CLI, tests) can report or compare them without re-reading.
pub fn run(opts: &ExtractStackEffectsOpts<'_>) -> Result<String> {
    let table = extract(opts)?;
    fs::write(opts.out, &table)
        .with_context(|| format!("failed writing stack-effect table {}", opts.out.display()))?;
    Ok(table)
}

/// Build the stack-effect table text (header + sorted rows) without writing it.
pub fn extract(opts: &ExtractStackEffectsOpts<'_>) -> Result<String> {
    let known = load_known_opcodes(opts.opcode_files);
    let rows = collect_rows(opts.clientscript_dir, &known)?;

    let mut out = String::with_capacity(HEADER.len() + rows.len() * 32);
    out.push_str(HEADER);
    for (name, effect) in &rows {
        out.push_str(name);
        out.push(' ');
        out.push_str(&effect.int_pops.to_string());
        out.push(' ');
        out.push_str(&effect.obj_pops.to_string());
        out.push(' ');
        out.push_str(&effect.long_pops.to_string());
        out.push(' ');
        out.push_str(&effect.int_pushes.to_string());
        out.push(' ');
        out.push_str(&effect.obj_pushes.to_string());
        out.push(' ');
        out.push_str(&effect.long_pushes.to_string());
        out.push('\n');
    }
    Ok(out)
}

/// Load every known opcode command name (first comma-field of each line) across
/// the books. Missing files are skipped, matching the Python's lenient read.
fn load_known_opcodes(opcode_files: &[PathBuf]) -> std::collections::HashSet<String> {
    let mut known = std::collections::HashSet::new();
    for path in opcode_files {
        let Ok(content) = fs::read_to_string(path) else {
            // Mirror the Python: a missing/unreadable book is simply ignored.
            continue;
        };
        for line in content.lines() {
            let name = line.split(',').next().unwrap_or("").trim();
            if !name.is_empty() {
                known.insert(name.to_string());
            }
        }
    }
    known
}

/// Glob the package for `*.java`, parse every handler, and return the kept rows
/// sorted by command name. A name found in more than one file keeps the last
/// parse, but the package has no duplicate handler names.
fn collect_rows(
    clientscript_dir: &Path,
    known: &std::collections::HashSet<String>,
) -> Result<Vec<(String, StackEffect)>> {
    let mut java_files = list_java_files(clientscript_dir)?;
    // Deterministic file order so a duplicate name (none exist today) would
    // resolve identically across runs.
    java_files.sort();

    let mut rows: BTreeMap<String, StackEffect> = BTreeMap::new();
    for path in &java_files {
        let text = fs::read_to_string(path)
            .with_context(|| format!("failed reading handler source {}", path.display()))?;
        for (name, body) in handlers(&text) {
            // Keep only handlers whose name is a known opcode (when a book was
            // supplied). An empty set means "no filter", matching the Python.
            if !known.is_empty() && !known.contains(name) {
                continue;
            }
            // Loops give variable stack effects we cannot count statically.
            if has_loop(body) {
                continue;
            }
            let effect = StackEffect {
                int_pops: count_pops(body, "isp"),
                obj_pops: count_pops(body, "osp"),
                long_pops: count_pops(body, "lsp"),
                int_pushes: count_pushes(body, "isp"),
                obj_pushes: count_pushes(body, "osp"),
                long_pushes: count_pushes(body, "lsp"),
            };
            // Only emit when there is direct stack evidence; otherwise leave the
            // opcode to the categorisation default rather than guess.
            if effect.is_empty() {
                continue;
            }
            rows.insert(name.to_string(), effect);
        }
    }
    Ok(rows.into_iter().collect())
}

/// List the `*.java` files directly in `dir` (non-recursive, like the original
/// single-file read scaled to the whole package).
fn list_java_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let entries = fs::read_dir(dir)
        .with_context(|| format!("failed reading clientscript dir {}", dir.display()))?;
    let mut files = Vec::new();
    for entry in entries {
        let path = entry
            .with_context(|| format!("failed reading dir entry in {}", dir.display()))?
            .path();
        if path.extension().is_some_and(|ext| ext == "java") {
            files.push(path);
        }
    }
    Ok(files)
}

/// Iterate `(handler_name, handler_body)` pairs in one Java source.
///
/// Faithful to the Python regex `public static final void (\w+)\(ClientScriptState
/// arg0\)\s*\{`: a state-only handler signature, with the brace-matched body
/// (the substring strictly between the opening `{` and its matching `}`).
/// Handlers with a trailing compile-time variant flag (`…, boolean arg1`) are
/// deliberately excluded, since their push is often conditional on that flag.
fn handlers(text: &str) -> impl Iterator<Item = (&str, &str)> {
    const SIG: &str = "public static final void ";
    let bytes = text.as_bytes();
    let mut search_from = 0usize;

    std::iter::from_fn(move || {
        while let Some(rel) = text[search_from..].find(SIG) {
            let sig_start = search_from + rel;
            let after_sig = sig_start + SIG.len();
            // Advance past this occurrence regardless of whether it matches, so
            // the scan always makes progress.
            search_from = after_sig;

            // Method name: a run of `\w` (`[A-Za-z0-9_]`).
            let name_start = after_sig;
            let name_end = name_start
                + bytes[name_start..]
                    .iter()
                    .take_while(|&&b| is_word_byte(b))
                    .count();
            if name_end == name_start {
                continue;
            }
            let name = &text[name_start..name_end];

            // Exactly `(ClientScriptState arg0)` follows the name.
            const PARAMS: &str = "(ClientScriptState arg0)";
            if !text[name_end..].starts_with(PARAMS) {
                continue;
            }
            let mut pos = name_end + PARAMS.len();

            // `\s*` then `{`.
            while pos < bytes.len() && bytes[pos].is_ascii_whitespace() {
                pos += 1;
            }
            if pos >= bytes.len() || bytes[pos] != b'{' {
                continue;
            }

            let body = brace_body(text, pos);
            return Some((name, body));
        }
        None
    })
}

/// Return the body of a method whose opening `{` is at byte index `open_brace`:
/// the substring between that brace and its depth-matched `}`. If the braces are
/// unbalanced (truncated source), returns everything after the opening brace,
/// matching the Python fallback.
fn brace_body(text: &str, open_brace: usize) -> &str {
    let bytes = text.as_bytes();
    let mut depth = 0i32;
    for (offset, &b) in bytes[open_brace..].iter().enumerate() {
        match b {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return &text[open_brace + 1..open_brace + offset];
                }
            }
            _ => {}
        }
    }
    &text[open_brace + 1..]
}

/// True when the body contains a `for`/`while` loop, faithful to the Python
/// `\b(for|while)\s*\(`: the keyword at a word boundary, optional whitespace,
/// then `(`.
fn has_loop(body: &str) -> bool {
    keyword_followed_by_paren(body, "for") || keyword_followed_by_paren(body, "while")
}

/// True when `keyword` appears at a word boundary in `body`, followed by
/// optional ASCII whitespace and then `(`.
fn keyword_followed_by_paren(body: &str, keyword: &str) -> bool {
    let bytes = body.as_bytes();
    let mut from = 0usize;
    while let Some(rel) = body[from..].find(keyword) {
        let start = from + rel;
        let end = start + keyword.len();
        from = start + 1;
        // Leading word boundary: previous byte is not a word char.
        if start > 0 && is_word_byte(bytes[start - 1]) {
            continue;
        }
        // `\s*` then `(`.
        let mut pos = end;
        while pos < bytes.len() && bytes[pos].is_ascii_whitespace() {
            pos += 1;
        }
        if pos < bytes.len() && bytes[pos] == b'(' {
            return true;
        }
    }
    false
}

/// Pops for one stack pointer (`isp`/`osp`/`lsp`): `--arg0.PTR` (boundary) +
/// `arg0.PTR--` + the summed `N` of every `arg0.PTR -= N`.
fn count_pops(body: &str, ptr: &str) -> u32 {
    let pre = format!("--arg0.{ptr}");
    let post = format!("arg0.{ptr}--");
    let assign = format!("arg0.{ptr} -= ");
    count_prefixed_word(body, &pre) + count_literal(body, &post) + sum_assign(body, &assign)
}

/// Pushes for one stack pointer: `++arg0.PTR` (boundary) + `arg0.PTR++` + the
/// summed `N` of every `arg0.PTR += N`.
fn count_pushes(body: &str, ptr: &str) -> u32 {
    let pre = format!("++arg0.{ptr}");
    let post = format!("arg0.{ptr}++");
    let assign = format!("arg0.{ptr} += ");
    count_prefixed_word(body, &pre) + count_literal(body, &post) + sum_assign(body, &assign)
}

/// Count non-overlapping occurrences of `needle` immediately followed by a word
/// boundary (the trailing `\b` in `--arg0\.isp\b` / `\+\+arg0\.isp\b`): the byte
/// after the match must not be a word char.
fn count_prefixed_word(haystack: &str, needle: &str) -> u32 {
    let bytes = haystack.as_bytes();
    let mut count = 0u32;
    let mut from = 0usize;
    while let Some(rel) = haystack[from..].find(needle) {
        let start = from + rel;
        let end = start + needle.len();
        // Non-overlapping, left-to-right (re.findall semantics).
        from = end;
        if end >= bytes.len() || !is_word_byte(bytes[end]) {
            count += 1;
        }
    }
    count
}

/// Count non-overlapping literal occurrences of `needle`.
fn count_literal(haystack: &str, needle: &str) -> u32 {
    let mut count = 0u32;
    let mut from = 0usize;
    while let Some(rel) = haystack[from..].find(needle) {
        from = from + rel + needle.len();
        count += 1;
    }
    count
}

/// Sum the decimal `N` of every `<prefix>N` occurrence, where `prefix` is e.g.
/// `arg0.isp -= ` and `N` is the immediately following run of ASCII digits
/// (faithful to `arg0\.isp -= (\d+)`). A prefix with no following digit
/// contributes nothing (the Python regex would not match it).
fn sum_assign(haystack: &str, prefix: &str) -> u32 {
    let bytes = haystack.as_bytes();
    let mut total = 0u32;
    let mut from = 0usize;
    while let Some(rel) = haystack[from..].find(prefix) {
        let digits_start = from + rel + prefix.len();
        from = digits_start;
        let digits_end = digits_start
            + bytes[digits_start..]
                .iter()
                .take_while(|b| b.is_ascii_digit())
                .count();
        if digits_end > digits_start {
            // The digit run is pure ASCII, so direct parse cannot fail.
            if let Ok(value) = haystack[digits_start..digits_end].parse::<u32>() {
                total += value;
            }
            from = digits_end;
        }
    }
    total
}

/// Java `\w` byte test: `[A-Za-z0-9_]`.
const fn is_word_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn handler_body_is_brace_matched() {
        let src = "public static final void foo(ClientScriptState arg0) { a { b } c }";
        let found: Vec<_> = handlers(src).collect();
        assert_eq!(found, vec![("foo", " a { b } c ")]);
    }

    #[test]
    fn handler_with_variant_flag_is_skipped() {
        // A trailing `boolean arg1` is not the state-only signature.
        let src = "public static final void db_find(ClientScriptState arg0, boolean arg1) { }";
        assert_eq!(handlers(src).count(), 0);
    }

    #[test]
    fn name_word_boundary_excludes_isp_substring() {
        // `--arg0.isproot` must NOT count as an `isp` pop (trailing `\b`).
        assert_eq!(count_pops("--arg0.isproot;", "isp"), 0);
        assert_eq!(count_pops("--arg0.isp;", "isp"), 1);
    }

    #[test]
    fn pops_sum_decrement_forms() {
        let body = "--arg0.isp; arg0.isp--; arg0.isp -= 3;";
        assert_eq!(count_pops(body, "isp"), 5);
    }

    #[test]
    fn pushes_sum_increment_forms() {
        let body = "++arg0.osp; arg0.osp++; arg0.osp += 2;";
        assert_eq!(count_pushes(body, "osp"), 4);
    }

    #[test]
    fn loop_bodies_are_detected() {
        assert!(has_loop("for (int i = 0;;) {}"));
        assert!(has_loop("while  (x) {}"));
        assert!(!has_loop("foreach(x)")); // `foreach` has no word boundary before `for`
        assert!(!has_loop("formatter(x)"));
    }

    #[test]
    fn empty_effect_detected() {
        assert!(StackEffect::default().is_empty());
        assert!(
            !StackEffect {
                int_pops: 1,
                ..StackEffect::default()
            }
            .is_empty()
        );
    }
}
