//! `generate-ts-ids` — join curated id→name maps with the runtime 948 pack,
//! validate every named id against the pack's real structure, and emit typed
//! TypeScript modules + a manifest the server imports.
//!
//! The cache cannot supply names (its `symbols/*.sym` are machine placeholders),
//! but it CAN supply existence and structure. This generator is the proof gate:
//! generation FAILS (exit 2) listing every violation if any named interface,
//! component, var, enum, struct, or script id is missing or structurally wrong
//! in the pack. Only the named subset is emitted; the guarantee comes from
//! generation-time validation, not from shipping the whole id universe.
//!
//! Read-only over the pack. Deterministic: ids sorted, no timestamps. The pack
//! files it reads are the single-file `.js5` containers under `--pack-root`,
//! addressed exactly as the `interfaces` / `varps` / `varbits` / config dump
//! subcommands address the flat cache (archive 3 interfaces, archive 2 config
//! groups for varp/varc/varbit, split archive 17 enums, split archive 22
//! structs, archive 12 scripts).

use crate::cache_bail;
use crate::config::{EnumEntry, parse_enum, parse_struct};
use crate::constants::{
    CONFIG_GROUP_VAR_BIT, CONFIG_GROUP_VAR_CLIENT, CONFIG_GROUP_VAR_PLAYER,
};
use crate::error::{Context, Result};
use crate::js5pack::PackArchive;
use crate::vars::{VarDomain, parse_var, parse_varbit};
use serde::Serialize;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Split-archive id packing: enums use group << 8 | file, structs group << 5.
const ENUM_BIT_SHIFT: u32 = 8;
const STRUCT_BIT_SHIFT: u32 = 5;

const GENERATED_HEADER: &str = "// GENERATED by rs3-cache-rs `generate-ts-ids` from the runtime pack + data/names/910 — do not edit.\n// Regenerate: cd tools/rs3-cache-rs && cargo run --release -- generate-ts-ids\n";

/// Resolved options for the `generate-ts-ids` subcommand.
#[derive(Debug)]
pub struct GenerateTsIdsOpts<'a> {
    /// Runtime pack root holding the `client.*.js5` files.
    pub pack_root: &'a Path,
    /// Curated name maps directory (`<data-dir>/names/910` by default).
    pub names_dir: &'a Path,
    /// Output directory for the generated TS modules + manifest.
    pub out_dir: &'a Path,
    /// Compare-only: write nothing, return drift list (CLI maps to exit 3).
    pub check: bool,
}

// ---------------------------------------------------------------------------
// Curated name maps
// ---------------------------------------------------------------------------

#[derive(Debug, serde::Deserialize)]
struct InterfaceNameEntry {
    name: String,
    #[serde(default)]
    components: BTreeMap<String, String>,
}

/// Parse `<id-string>` keys into `u32`, failing loudly on a non-numeric key.
fn parse_id(key: &str, domain: &str) -> Result<u32> {
    key.parse::<u32>()
        .with_context(|| format!("{domain} name map has non-numeric id key '{key}'"))
}

/// Read a simple `{ "<id>": "NAME" }` map, returning `(id, name)` pairs sorted by
/// id, or an empty list when the file is absent.
fn load_simple_map(names_dir: &Path, file: &str, domain: &str) -> Result<Vec<(u32, String)>> {
    let path = names_dir.join(file);
    if !path.is_file() {
        return Ok(Vec::new());
    }
    let text = fs::read_to_string(&path)
        .with_context(|| format!("failed reading {}", path.display()))?;
    let raw: BTreeMap<String, String> = serde_json::from_str(&text)
        .with_context(|| format!("failed parsing {}", path.display()))?;
    let mut out: Vec<(u32, String)> = Vec::with_capacity(raw.len());
    for (key, name) in raw {
        out.push((parse_id(&key, domain)?, name));
    }
    out.sort_by_key(|(id, _)| *id);
    Ok(out)
}

/// One named interface plus its named components, ids parsed and sorted.
struct InterfaceName {
    id: u32,
    name: String,
    components: Vec<(u32, String)>,
}

fn load_interfaces(names_dir: &Path) -> Result<Vec<InterfaceName>> {
    let path = names_dir.join("interfaces.json");
    if !path.is_file() {
        return Ok(Vec::new());
    }
    let text = fs::read_to_string(&path)
        .with_context(|| format!("failed reading {}", path.display()))?;
    let raw: BTreeMap<String, InterfaceNameEntry> = serde_json::from_str(&text)
        .with_context(|| format!("failed parsing {}", path.display()))?;
    let mut out = Vec::with_capacity(raw.len());
    for (key, entry) in raw {
        let id = parse_id(&key, "interfaces")?;
        let mut components: Vec<(u32, String)> = Vec::with_capacity(entry.components.len());
        for (ck, cname) in entry.components {
            components.push((
                parse_id(&ck, &format!("interfaces[{id}].components"))?,
                cname,
            ));
        }
        components.sort_by_key(|(cid, _)| *cid);
        out.push(InterfaceName {
            id,
            name: entry.name,
            components,
        });
    }
    out.sort_by_key(|i| i.id);
    Ok(out)
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/// Check that the names within one domain are unique `SCREAMING_SNAKE`
/// identifiers and that no id repeats, pushing every violation onto `violations`.
fn check_uniqueness(
    domain: &str,
    pairs: &[(u32, &str)],
    violations: &mut Vec<String>,
) {
    let mut seen_names: BTreeMap<&str, u32> = BTreeMap::new();
    let mut seen_ids: BTreeMap<u32, &str> = BTreeMap::new();
    for &(id, name) in pairs {
        if let Some(prev) = seen_names.insert(name, id) {
            violations.push(format!(
                "{domain}: duplicate name {name} (ids {prev} and {id})"
            ));
        }
        if let Some(prev) = seen_ids.insert(id, name) {
            violations.push(format!(
                "{domain}: duplicate id {id} (names {prev} and {name})"
            ));
        }
    }
}

/// Build the resolved, validated dataset, or `Err` listing every violation.
struct Resolved {
    interfaces: Vec<ResolvedInterface>,
    varps: Vec<(u32, String)>,
    varcs: Vec<(u32, String)>,
    varbits: Vec<ResolvedVarbit>,
    enums: Vec<ResolvedEnum>,
    structs: Vec<(u32, String)>,
    scripts: Vec<(u32, String)>,
}

struct ResolvedInterface {
    id: u32,
    name: String,
    component_count: usize,
    components: Vec<(u32, String)>,
}

struct ResolvedVarbit {
    id: u32,
    name: String,
    basevar: u32,
    startbit: u8,
    endbit: u8,
}

struct ResolvedEnum {
    id: u32,
    name: String,
    entry: EnumEntry,
}

/// Look up a split-archive config entry (enum/struct) by reconstructed id.
fn split_group_file(id: u32, bit_shift: u32) -> (u32, u32) {
    (id >> bit_shift, id & ((1 << bit_shift) - 1))
}

/// Fetch one file's bytes from a legacy config group (archive 2, file = id).
fn legacy_config_file(
    config: &PackArchive,
    group: u32,
    id: u32,
) -> Result<Option<Vec<u8>>> {
    let Some(files) = config.group_files(group)? else {
        return Ok(None);
    };
    Ok(files.get(&id).cloned())
}

/// Fetch one file's bytes from a split config archive (enum/struct).
fn split_config_file(
    pack: &PackArchive,
    id: u32,
    bit_shift: u32,
) -> Result<Option<Vec<u8>>> {
    let (group, file) = split_group_file(id, bit_shift);
    let Some(files) = pack.group_files(group)? else {
        return Ok(None);
    };
    Ok(files.get(&file).cloned())
}

fn resolve(opts: &GenerateTsIdsOpts<'_>) -> Result<Resolved> {
    let interface_names = load_interfaces(opts.names_dir)?;
    let player_var_names = load_simple_map(opts.names_dir, "varps.json", "varps")?;
    let client_var_names = load_simple_map(opts.names_dir, "varcs.json", "varcs")?;
    let varbit_names = load_simple_map(opts.names_dir, "varbits.json", "varbits")?;
    let enum_names = load_simple_map(opts.names_dir, "enums.json", "enums")?;
    let struct_names = load_simple_map(opts.names_dir, "structs.json", "structs")?;
    let script_names = load_simple_map(opts.names_dir, "scripts.json", "scripts")?;

    let mut violations: Vec<String> = Vec::new();

    // Domain-level uniqueness checks (ids + names) before touching the pack.
    let iface_pairs: Vec<(u32, &str)> = interface_names
        .iter()
        .map(|i| (i.id, i.name.as_str()))
        .collect();
    check_uniqueness("interfaces", &iface_pairs, &mut violations);
    for iface in &interface_names {
        let comp_pairs: Vec<(u32, &str)> = iface
            .components
            .iter()
            .map(|(cid, n)| (*cid, n.as_str()))
            .collect();
        check_uniqueness(
            &format!("interface {} components", iface.id),
            &comp_pairs,
            &mut violations,
        );
    }
    for (domain, pairs) in [
        ("varps", &player_var_names),
        ("varcs", &client_var_names),
        ("varbits", &varbit_names),
        ("enums", &enum_names),
        ("structs", &struct_names),
        ("scripts", &script_names),
    ] {
        let p: Vec<(u32, &str)> = pairs.iter().map(|(id, n)| (*id, n.as_str())).collect();
        check_uniqueness(domain, &p, &mut violations);
    }

    // Open the packs once each (only those a seeded domain needs). Each config
    // archive is opened WITH its sibling `.patch.js5` merged, so an id present
    // only in the overlay patch (e.g. an overlay-added enum group) validates as
    // present — exactly as the runtime client loads it. `open_with_patch` is a
    // plain open when no patch file exists (e.g. scripts), so this is safe for
    // every archive.
    let interfaces_pack = PackArchive::open_with_patch(&opts.pack_root.join("client.interfaces.js5"))?;
    let config_pack = PackArchive::open_with_patch(&opts.pack_root.join("client.config.js5"))?;
    let enum_pack = PackArchive::open_with_patch(&opts.pack_root.join("client.enum.config.js5"))?;
    let struct_pack = PackArchive::open_with_patch(&opts.pack_root.join("client.struct.config.js5"))?;
    let scripts_pack = PackArchive::open_with_patch(&opts.pack_root.join("client.scripts.js5"))?;

    // Interfaces (archive 3): group = interface id, files = components.
    let mut interfaces = Vec::new();
    for iface in &interface_names {
        let Some(files) = interfaces_pack.group_files(iface.id)? else {
            violations.push(format!(
                "interface {} ({}) absent from archive 3",
                iface.id, iface.name
            ));
            continue;
        };
        let component_count = files.len();
        let mut components = Vec::with_capacity(iface.components.len());
        for (cid, cname) in &iface.components {
            if !files.contains_key(cid) {
                violations.push(format!(
                    "interface {} component {} ({}) has no file in the interface group",
                    iface.id, cid, cname
                ));
                continue;
            }
            if usize::try_from(*cid).is_ok_and(|c| c >= component_count) {
                violations.push(format!(
                    "interface {} component {} ({}) >= componentCount {component_count}",
                    iface.id, cid, cname
                ));
                continue;
            }
            components.push((*cid, cname.clone()));
        }
        interfaces.push(ResolvedInterface {
            id: iface.id,
            name: iface.name.clone(),
            component_count,
            components,
        });
    }

    // Varps (archive 2, group 60): file = id.
    let mut player_var_ids = Vec::new();
    for (id, name) in &player_var_names {
        match legacy_config_file(&config_pack, CONFIG_GROUP_VAR_PLAYER, *id)? {
            Some(bytes) => match parse_var(VarDomain::Player, *id, &bytes) {
                Ok(_) => player_var_ids.push((*id, name.clone())),
                Err(e) => violations.push(format!("varp {id} ({name}) failed to parse: {e}")),
            },
            None => violations.push(format!("varp {id} ({name}) absent from player var group")),
        }
    }

    // Varcs (archive 2, group 62): file = id.
    let mut client_var_ids = Vec::new();
    for (id, name) in &client_var_names {
        match legacy_config_file(&config_pack, CONFIG_GROUP_VAR_CLIENT, *id)? {
            Some(bytes) => match parse_var(VarDomain::Client, *id, &bytes) {
                Ok(_) => client_var_ids.push((*id, name.clone())),
                Err(e) => violations.push(format!("varc {id} ({name}) failed to parse: {e}")),
            },
            None => violations.push(format!("varc {id} ({name}) absent from client var group")),
        }
    }

    // Varbits (archive 2, group 69): file = id; record bit packing.
    let mut varbits = Vec::new();
    for (id, name) in &varbit_names {
        match legacy_config_file(&config_pack, CONFIG_GROUP_VAR_BIT, *id)? {
            Some(bytes) => match parse_varbit(*id, &bytes) {
                Ok(entry) => match (entry.base_var, entry.start_bit, entry.end_bit) {
                    (Some(basevar), Some(startbit), Some(endbit)) => varbits.push(ResolvedVarbit {
                        id: *id,
                        name: name.clone(),
                        basevar,
                        startbit,
                        endbit,
                    }),
                    _ => violations.push(format!(
                        "varbit {id} ({name}) missing basevar/startbit/endbit"
                    )),
                },
                Err(e) => violations.push(format!("varbit {id} ({name}) failed to parse: {e}")),
            },
            None => violations.push(format!("varbit {id} ({name}) absent from varbit group")),
        }
    }

    // Enums (split archive 17): record the decoded table.
    let mut enums = Vec::new();
    for (id, name) in &enum_names {
        match split_config_file(&enum_pack, *id, ENUM_BIT_SHIFT)? {
            Some(bytes) => match parse_enum(*id, &bytes) {
                Ok(entry) => enums.push(ResolvedEnum {
                    id: *id,
                    name: name.clone(),
                    entry,
                }),
                Err(e) => violations.push(format!("enum {id} ({name}) failed to parse: {e}")),
            },
            None => violations.push(format!("enum {id} ({name}) absent from archive 17")),
        }
    }

    // Structs (split archive 22): existence + parse only (params not embedded).
    let mut structs = Vec::new();
    for (id, name) in &struct_names {
        match split_config_file(&struct_pack, *id, STRUCT_BIT_SHIFT)? {
            Some(bytes) => match parse_struct(*id, &bytes) {
                Ok(_) => structs.push((*id, name.clone())),
                Err(e) => violations.push(format!("struct {id} ({name}) failed to parse: {e}")),
            },
            None => violations.push(format!("struct {id} ({name}) absent from archive 22")),
        }
    }

    // Scripts (archive 12): group present.
    let mut scripts = Vec::new();
    for (id, name) in &script_names {
        if scripts_pack.group_container(*id).is_some() {
            scripts.push((*id, name.clone()));
        } else {
            violations.push(format!("script {id} ({name}) absent from archive 12"));
        }
    }

    if !violations.is_empty() {
        violations.sort();
        let mut msg = format!(
            "generate-ts-ids: {} validation violation(s) against the pack:\n",
            violations.len()
        );
        for v in &violations {
            let _ = writeln!(msg, "  - {v}");
        }
        cache_bail!("{msg}");
    }

    Ok(Resolved {
        interfaces,
        varps: player_var_ids,
        varcs: client_var_ids,
        varbits,
        enums,
        structs,
        scripts,
    })
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

/// `PascalCase` a `SCREAMING_SNAKE` identifier (`SLOT_GRID` -> `SlotGrid`).
fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for part in name.split('_').filter(|p| !p.is_empty()) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.extend(chars.flat_map(char::to_lowercase));
        }
    }
    out
}

fn ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('\'');
    out
}

fn type_char_label(c: Option<u8>) -> String {
    match c {
        Some(b) if b.is_ascii_graphic() => ts_string(&(b as char).to_string()),
        Some(b) => format!("'\\u{b:04x}'"),
        None => "null".to_owned(),
    }
}

fn render_interfaces(resolved: &Resolved) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');
    out.push_str("export const Interfaces = {\n");
    for iface in &resolved.interfaces {
        let _ = writeln!(out, "    {}: {},", iface.name, iface.id);
    }
    out.push_str("} as const;\n");

    for iface in &resolved.interfaces {
        if iface.components.is_empty() {
            continue;
        }
        let obj = pascal_case(&iface.name);
        let _ = write!(out, "\nexport const {obj} = {{\n    id: {},\n    com: {{\n", iface.id);
        for (cid, cname) in &iface.components {
            let _ = writeln!(out, "        {cname}: {cid},");
        }
        let _ = write!(
            out,
            "    }},\n    componentCount: {},\n}} as const;\n",
            iface.component_count
        );
    }
    out
}

fn render_simple(export_name: &str, pairs: &[(u32, String)]) -> String {
    let mut out = String::from(GENERATED_HEADER);
    let _ = write!(out, "\nexport const {export_name} = {{\n");
    for (id, name) in pairs {
        let _ = writeln!(out, "    {name}: {id},");
    }
    out.push_str("} as const;\n");
    out
}

fn render_varbits(resolved: &Resolved) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\nexport const Varbits = {\n");
    for vb in &resolved.varbits {
        let _ = writeln!(out, "    {}: {},", vb.name, vb.id);
    }
    out.push_str("} as const;\n\n");
    out.push_str(
        "export const VarbitDefs: Record<number, { basevar: number; startbit: number; endbit: number }> = {\n",
    );
    for vb in &resolved.varbits {
        let _ = writeln!(
            out,
            "    {}: {{ basevar: {}, startbit: {}, endbit: {} }},",
            vb.id, vb.basevar, vb.startbit, vb.endbit
        );
    }
    out.push_str("};\n");
    out
}

fn render_enums(resolved: &Resolved) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\nexport const Enums = {\n");
    for en in &resolved.enums {
        let _ = writeln!(out, "    {}: {},", en.name, en.id);
    }
    out.push_str("} as const;\n");

    for en in &resolved.enums {
        let e = &en.entry;
        let in_type = type_char_label(e.input_type_char);
        let out_type = type_char_label(e.output_type_char);
        let default = match &e.default {
            Some(crate::config::ScalarValue::Int(i)) => i.to_string(),
            Some(crate::config::ScalarValue::Long(l)) => l.to_string(),
            Some(crate::config::ScalarValue::Str(s)) => ts_string(s),
            None => "null".to_owned(),
        };
        let _ = write!(
            out,
            "\nexport const {}: {{ inType: string | null, outType: string | null, default: number | string | null, map: Record<number, number | string> }} = {{\n",
            en.name
        );
        let _ = writeln!(out, "    inType: {in_type},");
        let _ = writeln!(out, "    outType: {out_type},");
        let _ = writeln!(out, "    default: {default},");
        out.push_str("    map: {\n");
        let mut pairs: Vec<(i32, String)> = e
            .values
            .iter()
            .map(|p| {
                let v = match &p.value {
                    crate::config::ScalarValue::Int(i) => i.to_string(),
                    crate::config::ScalarValue::Long(l) => l.to_string(),
                    crate::config::ScalarValue::Str(s) => ts_string(s),
                };
                (p.key, v)
            })
            .collect();
        pairs.sort_by_key(|(k, _)| *k);
        for (k, v) in pairs {
            let _ = writeln!(out, "        {k}: {v},");
        }
        out.push_str("    },\n};\n");
    }
    out
}

/// Build the `(file_name, body)` pairs for every emitted module in a stable order.
fn render_all(resolved: &Resolved) -> Vec<(String, String)> {
    vec![
        ("interfaces.ts".to_owned(), render_interfaces(resolved)),
        (
            "varps.ts".to_owned(),
            render_simple("Varps", &resolved.varps),
        ),
        (
            "varcs.ts".to_owned(),
            render_simple("Varcs", &resolved.varcs),
        ),
        ("varbits.ts".to_owned(), render_varbits(resolved)),
        ("enums.ts".to_owned(), render_enums(resolved)),
        (
            "structs.ts".to_owned(),
            render_simple("Structs", &resolved.structs),
        ),
        (
            "scripts.ts".to_owned(),
            render_simple("Scripts", &resolved.scripts),
        ),
    ]
}

#[derive(Serialize)]
struct Manifest {
    schema: &'static str,
    counts: BTreeMap<&'static str, usize>,
    files: BTreeMap<String, String>,
}

fn build_manifest(resolved: &Resolved, files: &[(String, String)]) -> String {
    let mut counts: BTreeMap<&'static str, usize> = BTreeMap::new();
    counts.insert("interfaces", resolved.interfaces.len());
    counts.insert(
        "interface_components",
        resolved.interfaces.iter().map(|i| i.components.len()).sum(),
    );
    counts.insert("varps", resolved.varps.len());
    counts.insert("varcs", resolved.varcs.len());
    counts.insert("varbits", resolved.varbits.len());
    counts.insert("enums", resolved.enums.len());
    counts.insert("structs", resolved.structs.len());
    counts.insert("scripts", resolved.scripts.len());

    let mut hashes: BTreeMap<String, String> = BTreeMap::new();
    for (name, body) in files {
        hashes.insert(name.clone(), sha256_hex(body.as_bytes()));
    }
    let manifest = Manifest {
        schema: "ts-idgen/v1",
        counts,
        files: hashes,
    };
    let mut json = serde_json::to_string_pretty(&manifest).expect("manifest serializes");
    json.push('\n');
    json
}

/// Run the `generate-ts-ids` subcommand. Returns `true` when `--check` found
/// drift (the CLI maps that to exit code 3).
pub fn run(opts: &GenerateTsIdsOpts<'_>) -> Result<bool> {
    let resolved = resolve(opts)?;
    let mut files = render_all(&resolved);
    files.push(("manifest.json".to_owned(), build_manifest(&resolved, &files)));

    if opts.check {
        let mut drift: Vec<String> = Vec::new();
        for (name, body) in &files {
            let path = opts.out_dir.join(name);
            let on_disk = fs::read_to_string(&path).unwrap_or_default();
            if on_disk != *body {
                drift.push(name.clone());
            }
        }
        if drift.is_empty() {
            println!("generate-ts-ids --check: all {} file(s) up to date", files.len());
            return Ok(false);
        }
        println!("generate-ts-ids --check: {} file(s) differ:", drift.len());
        for name in &drift {
            println!("  - {name}");
        }
        return Ok(true);
    }

    fs::create_dir_all(opts.out_dir)
        .with_context(|| format!("failed creating {}", opts.out_dir.display()))?;
    for (name, body) in &files {
        let path = opts.out_dir.join(name);
        fs::write(&path, body)
            .with_context(|| format!("failed writing {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(false)
}

// ---------------------------------------------------------------------------
// SHA-256 (self-contained; no new crate dependency)
// ---------------------------------------------------------------------------

const SHA256_K: [u32; 64] = [
    0x428a_2f98, 0x7137_4491, 0xb5c0_fbcf, 0xe9b5_dba5, 0x3956_c25b, 0x59f1_11f1, 0x923f_82a4,
    0xab1c_5ed5, 0xd807_aa98, 0x1283_5b01, 0x2431_85be, 0x550c_7dc3, 0x72be_5d74, 0x80de_b1fe,
    0x9bdc_06a7, 0xc19b_f174, 0xe49b_69c1, 0xefbe_4786, 0x0fc1_9dc6, 0x240c_a1cc, 0x2de9_2c6f,
    0x4a74_84aa, 0x5cb0_a9dc, 0x76f9_88da, 0x983e_5152, 0xa831_c66d, 0xb003_27c8, 0xbf59_7fc7,
    0xc6e0_0bf3, 0xd5a7_9147, 0x06ca_6351, 0x1429_2967, 0x27b7_0a85, 0x2e1b_2138, 0x4d2c_6dfc,
    0x5338_0d13, 0x650a_7354, 0x766a_0abb, 0x81c2_c92e, 0x9272_2c85, 0xa2bf_e8a1, 0xa81a_664b,
    0xc24b_8b70, 0xc76c_51a3, 0xd192_e819, 0xd699_0624, 0xf40e_3585, 0x106a_a070, 0x19a4_c116,
    0x1e37_6c08, 0x2748_774c, 0x34b0_bcb5, 0x391c_0cb3, 0x4ed8_aa4a, 0x5b9c_ca4f, 0x682e_6ff3,
    0x748f_82ee, 0x78a5_636f, 0x84c8_7814, 0x8cc7_0208, 0x90be_fffa, 0xa450_6ceb, 0xbef9_a3f7,
    0xc671_78f2,
];

/// Lower-case hex SHA-256 of the input bytes (RFC 6234), used to anchor the
/// manifest. Self-contained so the crate needs no new dependency.
fn sha256_hex(data: &[u8]) -> String {
    let mut h: [u32; 8] = [
        0x6a09_e667, 0xbb67_ae85, 0x3c6e_f372, 0xa54f_f53a, 0x510e_527f, 0x9b05_688c, 0x1f83_d9ab,
        0x5be0_cd19,
    ];

    let bit_len = (data.len() as u64).wrapping_mul(8);
    let mut msg = data.to_vec();
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    let mut w = [0u32; 64];
    for chunk in msg.chunks_exact(64) {
        for (i, word) in w.iter_mut().enumerate().take(16) {
            let j = i * 4;
            *word = u32::from_be_bytes([chunk[j], chunk[j + 1], chunk[j + 2], chunk[j + 3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }

        let mut v = h;
        for i in 0..64 {
            let s1 = v[4].rotate_right(6) ^ v[4].rotate_right(11) ^ v[4].rotate_right(25);
            let ch = (v[4] & v[5]) ^ ((!v[4]) & v[6]);
            let t1 = v[7]
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(SHA256_K[i])
                .wrapping_add(w[i]);
            let s0 = v[0].rotate_right(2) ^ v[0].rotate_right(13) ^ v[0].rotate_right(22);
            let maj = (v[0] & v[1]) ^ (v[0] & v[2]) ^ (v[1] & v[2]);
            let t2 = s0.wrapping_add(maj);
            v[7] = v[6];
            v[6] = v[5];
            v[5] = v[4];
            v[4] = v[3].wrapping_add(t1);
            v[3] = v[2];
            v[2] = v[1];
            v[1] = v[0];
            v[0] = t1.wrapping_add(t2);
        }
        for (hi, vi) in h.iter_mut().zip(v.iter()) {
            *hi = hi.wrapping_add(*vi);
        }
    }

    let mut out = String::with_capacity(64);
    for word in h {
        let _ = write!(out, "{word:08x}");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha256_matches_known_vectors() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            sha256_hex(b"The quick brown fox jumps over the lazy dog"),
            "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592"
        );
    }

    #[test]
    fn pascal_case_handles_snake() {
        assert_eq!(pascal_case("SLOT_GRID"), "SlotGrid");
        assert_eq!(pascal_case("BANK"), "Bank");
        assert_eq!(pascal_case("LEVEL_UP_OVERLAY"), "LevelUpOverlay");
    }

    #[test]
    fn uniqueness_flags_duplicate_id_and_name() {
        let mut v = Vec::new();
        check_uniqueness(
            "x",
            &[(1, "A"), (2, "A"), (1, "B")],
            &mut v,
        );
        assert!(v.iter().any(|m| m.contains("duplicate name A")));
        assert!(v.iter().any(|m| m.contains("duplicate id 1")));
    }

    #[test]
    fn split_group_file_packing() {
        // enum 1479 -> group 5, file 199.
        assert_eq!(split_group_file(1479, ENUM_BIT_SHIFT), (5, 199));
        // struct: group<<5 | file.
        assert_eq!(split_group_file((3 << 5) | 7, STRUCT_BIT_SHIFT), (3, 7));
    }
}
